import { experimental_extendTheme as extendTheme } from "@mui/material/styles";
import { getComponentOverrides } from "./overrides";

// ─── Sneat Theme Color Schemes (light + dark) ───
const colorSchemes = {
  light: {
    palette: {
      primary: {
        main: "#696cff",
        light: "#8587ff",
        dark: "#5f61e6",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.38)",
      },
      secondary: {
        main: "#8592a3",
        light: "#9da8b7",
        dark: "#788393",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.38)",
      },
      error: {
        main: "#ff3e1d",
        light: "#ff6548",
        dark: "#e6381a",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.38)",
      },
      warning: {
        main: "#ffab00",
        light: "#ffbc33",
        dark: "#e69a00",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.38)",
      },
      info: {
        main: "#03c3ec",
        light: "#35cff0",
        dark: "#03b0d4",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.38)",
      },
      success: {
        main: "#71dd37",
        light: "#8de45f",
        dark: "#66c732",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.38)",
      },
      text: {
        primary: "#566a7f",
        secondary: "#697a8d",
        disabled: "rgb(var(--mui-mainColorChannels-light) / 0.4)",
        primaryChannel: "var(--mui-mainColorChannels-light)",
        secondaryChannel: "var(--mui-mainColorChannels-light)",
      },
      divider: "#d9dee3",
      dividerChannel: "var(--mui-mainColorChannels-light)",
      background: {
        default: "#f5f5f9",
        paper: "#fff",
      },
      action: {
        active: "rgb(var(--mui-mainColorChannels-light) / 0.6)",
        hover: "rgb(var(--mui-mainColorChannels-light) / 0.04)",
        selected: "rgb(var(--mui-mainColorChannels-light) / 0.08)",
        disabled: "rgb(var(--mui-mainColorChannels-light) / 0.3)",
        disabledBackground: "rgb(var(--mui-mainColorChannels-light) / 0.12)",
        focus: "rgb(var(--mui-mainColorChannels-light) / 0.1)",
        focusOpacity: 0.1,
        activeChannel: "var(--mui-mainColorChannels-light)",
        selectedChannel: "var(--mui-mainColorChannels-light)",
      },
      Alert: {
        errorColor: "var(--mui-palette-error-main)",
        warningColor: "var(--mui-palette-warning-main)",
        infoColor: "var(--mui-palette-info-main)",
        successColor: "var(--mui-palette-success-main)",
        errorStandardBg: "#ffe7e3",
        warningStandardBg: "#fff3d6",
        infoStandardBg: "#d6f7fd",
        successStandardBg: "#e8fbdb",
        errorFilledColor: "#fff",
        warningFilledColor: "#fff",
        infoFilledColor: "#fff",
        successFilledColor: "#fff",
        errorFilledBg: "var(--mui-palette-error-main)",
        warningFilledBg: "var(--mui-palette-warning-main)",
        infoFilledBg: "var(--mui-palette-info-main)",
        successFilledBg: "var(--mui-palette-success-main)",
      },
      Avatar: { defaultBg: "#eeedf0" },
      Chip: { defaultBorder: "var(--mui-palette-divider)" },
      FilledInput: {
        bg: "rgb(var(--mui-mainColorChannels-light) / 0.06)",
        hoverBg: "rgb(var(--mui-mainColorChannels-light) / 0.08)",
        disabledBg: "rgb(var(--mui-mainColorChannels-light) / 0.06)",
      },
      SnackbarContent: {
        bg: "#233446",
        color: "#fff",
      },
      Switch: {
        defaultColor: "var(--mui-palette-common-white)",
        defaultDisabledColor: "var(--mui-palette-common-white)",
        primaryDisabledColor: "var(--mui-palette-common-white)",
        secondaryDisabledColor: "var(--mui-palette-common-white)",
        errorDisabledColor: "var(--mui-palette-common-white)",
        warningDisabledColor: "var(--mui-palette-common-white)",
        infoDisabledColor: "var(--mui-palette-common-white)",
        successDisabledColor: "var(--mui-palette-common-white)",
      },
      Tooltip: { bg: "#233446" },
      TableCell: { border: "#d9dee3" },
      customColors: {
        bodyBg: "#f5f5f9",
        chatBg: "#f5f5f9",
        greyLightBg: "#fafafa",
        inputBorder: "rgb(var(--mui-mainColorChannels-light) / 0.22)",
        tableHeaderBg: "#f9fafc",
        tooltipText: "#fff",
        trackBg: "#f0f2f8",
      },
    },
  },
  dark: {
    palette: {
      primary: {
        main: "#696cff",
        light: "#8587ff",
        dark: "#5f61e6",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-primary-mainChannel) / 0.38)",
      },
      secondary: {
        main: "#8592a3",
        light: "#9da8b7",
        dark: "#788393",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-secondary-mainChannel) / 0.38)",
      },
      error: {
        main: "#ff3e1d",
        light: "#ff6548",
        dark: "#e6381a",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-error-mainChannel) / 0.38)",
      },
      warning: {
        main: "#ffab00",
        light: "#ffbc33",
        dark: "#e69a00",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-warning-mainChannel) / 0.38)",
      },
      info: {
        main: "#03c3ec",
        light: "#35cff0",
        dark: "#03b0d4",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-info-mainChannel) / 0.38)",
      },
      success: {
        main: "#71dd37",
        light: "#8de45f",
        dark: "#66c732",
        contrastText: "#fff",
        lighterOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.08)",
        lightOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.16)",
        mainOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.24)",
        darkOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.32)",
        darkerOpacity: "rgb(var(--mui-palette-success-mainChannel) / 0.38)",
      },
      text: {
        primary: "rgb(var(--mui-mainColorChannels-dark) / 0.9)",
        secondary: "rgb(var(--mui-mainColorChannels-dark) / 0.7)",
        disabled: "rgb(var(--mui-mainColorChannels-dark) / 0.4)",
        primaryChannel: "var(--mui-mainColorChannels-dark)",
        secondaryChannel: "var(--mui-mainColorChannels-dark)",
      },
      divider: "rgb(var(--mui-mainColorChannels-dark) / 0.12)",
      dividerChannel: "var(--mui-mainColorChannels-dark)",
      background: {
        default: "#232333",
        paper: "#2b2c40",
      },
      action: {
        active: "rgb(var(--mui-mainColorChannels-dark) / 0.6)",
        hover: "rgb(var(--mui-mainColorChannels-dark) / 0.04)",
        selected: "rgb(var(--mui-mainColorChannels-dark) / 0.08)",
        disabled: "rgb(var(--mui-mainColorChannels-dark) / 0.3)",
        disabledBackground: "rgb(var(--mui-mainColorChannels-dark) / 0.12)",
        focus: "rgb(var(--mui-mainColorChannels-dark) / 0.1)",
        focusOpacity: 0.1,
        activeChannel: "var(--mui-mainColorChannels-dark)",
        selectedChannel: "var(--mui-mainColorChannels-dark)",
      },
      Alert: {
        errorColor: "var(--mui-palette-error-main)",
        warningColor: "var(--mui-palette-warning-main)",
        infoColor: "var(--mui-palette-info-main)",
        successColor: "var(--mui-palette-success-main)",
        errorStandardBg: "var(--mui-palette-error-lightOpacity)",
        warningStandardBg: "var(--mui-palette-warning-lightOpacity)",
        infoStandardBg: "var(--mui-palette-info-lightOpacity)",
        successStandardBg: "var(--mui-palette-success-lightOpacity)",
        errorFilledColor: "#fff",
        warningFilledColor: "#fff",
        infoFilledColor: "#fff",
        successFilledColor: "#fff",
        errorFilledBg: "var(--mui-palette-error-main)",
        warningFilledBg: "var(--mui-palette-warning-main)",
        infoFilledBg: "var(--mui-palette-info-main)",
        successFilledBg: "var(--mui-palette-success-main)",
      },
      Avatar: { defaultBg: "#3a3b55" },
      Chip: { defaultBorder: "var(--mui-palette-divider)" },
      FilledInput: {
        bg: "rgb(var(--mui-mainColorChannels-dark) / 0.06)",
        hoverBg: "rgb(var(--mui-mainColorChannels-dark) / 0.08)",
        disabledBg: "rgb(var(--mui-mainColorChannels-dark) / 0.06)",
      },
      SnackbarContent: {
        bg: "#cfcce4",
        color: "#2b2c40",
      },
      Switch: {
        defaultColor: "var(--mui-palette-common-white)",
        defaultDisabledColor: "var(--mui-palette-common-white)",
        primaryDisabledColor: "var(--mui-palette-common-white)",
        secondaryDisabledColor: "var(--mui-palette-common-white)",
        errorDisabledColor: "var(--mui-palette-common-white)",
        warningDisabledColor: "var(--mui-palette-common-white)",
        infoDisabledColor: "var(--mui-palette-common-white)",
        successDisabledColor: "var(--mui-palette-common-white)",
      },
      Tooltip: { bg: "#cfcce4" },
      TableCell: { border: "var(--mui-palette-divider)" },
      customColors: {
        bodyBg: "#232333",
        chatBg: "#2f3049",
        greyLightBg: "#33334a",
        inputBorder: "rgb(var(--mui-mainColorChannels-dark) / 0.22)",
        tableHeaderBg: "#33334a",
        tooltipText: "#2b2c40",
        trackBg: "#3a3b55",
      },
    },
  },
};

// ─── Shadows ───
function getShadows(mode: "light" | "dark") {
  const color = `var(--mui-mainColorChannels-${mode}Shadow)`;
  return [
    "none",
    `0px 2px 1px -1px rgb(${color} / 0.2),0px 1px 1px 0px rgb(${color} / 0.14),0px 1px 3px 0px rgb(${color} / 0.12)`,
    `0px 3px 1px -2px rgb(${color} / 0.2),0px 2px 2px 0px rgb(${color} / 0.14),0px 1px 5px 0px rgb(${color} / 0.12)`,
    `0px 3px 3px -2px rgb(${color} / 0.2),0px 3px 4px 0px rgb(${color} / 0.14),0px 1px 8px 0px rgb(${color} / 0.12)`,
    `0px 2px 4px -1px rgb(${color} / 0.2),0px 4px 5px 0px rgb(${color} / 0.14),0px 1px 10px 0px rgb(${color} / 0.12)`,
    `0px 3px 5px -1px rgb(${color} / 0.2),0px 5px 8px 0px rgb(${color} / 0.14),0px 1px 14px 0px rgb(${color} / 0.12)`,
    `0px 3px 5px -1px rgb(${color} / 0.2),0px 6px 10px 0px rgb(${color} / 0.14),0px 1px 18px 0px rgb(${color} / 0.12)`,
    `0px 4px 5px -2px rgb(${color} / 0.2),0px 7px 10px 1px rgb(${color} / 0.14),0px 2px 16px 1px rgb(${color} / 0.12)`,
    `0px 5px 5px -3px rgb(${color} / 0.2),0px 8px 10px 1px rgb(${color} / 0.14),0px 3px 14px 2px rgb(${color} / 0.12)`,
    `0px 5px 6px -3px rgb(${color} / 0.2),0px 9px 12px 1px rgb(${color} / 0.14),0px 3px 16px 2px rgb(${color} / 0.12)`,
    `0px 6px 6px -3px rgb(${color} / 0.2),0px 10px 14px 1px rgb(${color} / 0.14),0px 4px 18px 3px rgb(${color} / 0.12)`,
    `0px 6px 7px -4px rgb(${color} / 0.2),0px 11px 15px 1px rgb(${color} / 0.14),0px 4px 20px 3px rgb(${color} / 0.12)`,
    `0px 7px 8px -4px rgb(${color} / 0.2),0px 12px 17px 2px rgb(${color} / 0.14),0px 5px 22px 4px rgb(${color} / 0.12)`,
    `0px 7px 8px -4px rgb(${color} / 0.2),0px 13px 19px 2px rgb(${color} / 0.14),0px 5px 24px 4px rgb(${color} / 0.12)`,
    `0px 7px 9px -4px rgb(${color} / 0.2),0px 14px 21px 2px rgb(${color} / 0.14),0px 5px 26px 4px rgb(${color} / 0.12)`,
    `0px 8px 9px -5px rgb(${color} / 0.2),0px 15px 22px 2px rgb(${color} / 0.14),0px 6px 28px 5px rgb(${color} / 0.12)`,
    `0px 8px 10px -5px rgb(${color} / 0.2),0px 16px 24px 2px rgb(${color} / 0.14),0px 6px 30px 5px rgb(${color} / 0.12)`,
    `0px 8px 11px -5px rgb(${color} / 0.2),0px 17px 26px 2px rgb(${color} / 0.14),0px 6px 32px 5px rgb(${color} / 0.12)`,
    `0px 9px 11px -5px rgb(${color} / 0.2),0px 18px 28px 2px rgb(${color} / 0.14),0px 7px 34px 6px rgb(${color} / 0.12)`,
    `0px 9px 12px -6px rgb(${color} / 0.2),0px 19px 29px 2px rgb(${color} / 0.14),0px 7px 36px 6px rgb(${color} / 0.12)`,
    `0px 10px 13px -6px rgb(${color} / 0.2),0px 20px 31px 3px rgb(${color} / 0.14),0px 8px 38px 7px rgb(${color} / 0.12)`,
    `0px 10px 13px -6px rgb(${color} / 0.2),0px 21px 33px 3px rgb(${color} / 0.14),0px 8px 40px 7px rgb(${color} / 0.12)`,
    `0px 10px 14px -6px rgb(${color} / 0.2),0px 22px 35px 3px rgb(${color} / 0.14),0px 8px 42px 7px rgb(${color} / 0.12)`,
    `0px 11px 14px -7px rgb(${color} / 0.2),0px 23px 36px 3px rgb(${color} / 0.14),0px 9px 44px 8px rgb(${color} / 0.12)`,
    `0px 11px 15px -7px rgb(${color} / 0.2),0px 24px 38px 3px rgb(${color} / 0.14),0px 9px 46px 8px rgb(${color} / 0.12)`,
  ] as const;
}

function getCustomShadows(mode: "light" | "dark") {
  const s = mode === "light" ? "light" : "dark";
  return {
    xs: `0px 2px 4px rgb(var(--mui-mainColorChannels-${s}Shadow) / ${mode === "light" ? 0.16 : 0.2})`,
    sm: `0px 3px 6px rgb(var(--mui-mainColorChannels-${s}Shadow) / ${mode === "light" ? 0.18 : 0.22})`,
    md: `0px 4px 10px rgb(var(--mui-mainColorChannels-${s}Shadow) / ${mode === "light" ? 0.2 : 0.24})`,
    lg: `0px 6px 16px rgb(var(--mui-mainColorChannels-${s}Shadow) / ${mode === "light" ? 0.22 : 0.26})`,
    xl: `0px 8px 28px rgb(var(--mui-mainColorChannels-${s}Shadow) / ${mode === "light" ? 0.24 : 0.28})`,
  };
}

// ─── Typography (Sneat: Public Sans) ───
const typography = {
  fontFamily: [
    '"Public Sans"',
    "-apple-system",
    "BlinkMacSystemFont",
    '"Segoe UI"',
    "Oxygen",
    "Ubuntu",
    "Cantarell",
    '"Fira Sans"',
    '"Droid Sans"',
    '"Helvetica Neue"',
    "sans-serif",
  ].join(","),
  fontSize: 13.125,
  h1: { fontSize: "2.375rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  h2: { fontSize: "2rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  h3: { fontSize: "1.625rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  h4: { fontSize: "1.375rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  h5: { fontSize: "1.125rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  h6: { fontSize: "0.9375rem", fontWeight: 500, lineHeight: 1.1, color: "#566a7f" },
  subtitle1: { fontSize: "0.9375rem", lineHeight: 1.53 },
  subtitle2: { fontSize: "0.8125rem", fontWeight: 400, lineHeight: 1.53 },
  body1: { fontSize: "0.9375rem", lineHeight: 1.53 },
  body2: { fontSize: "0.8125rem", lineHeight: 1.53 },
  button: { fontSize: "0.9375rem", lineHeight: 1.53, textTransform: "none" as const },
  caption: { fontSize: "0.8125rem", lineHeight: 1.385, letterSpacing: "0.4px" },
  overline: { fontSize: "0.75rem", lineHeight: 1.167, letterSpacing: "0.8px" },
};

// ─── Theme (using extendTheme for CSS vars) ───
export function createUiTheme(mode: "light" | "dark" = "light") {
  return extendTheme({
    colorSchemes,
    components: getComponentOverrides() as unknown,
    spacing: (factor: number) => `${0.25 * factor}rem`,
    shape: {
      borderRadius: 6,
      customBorderRadius: { xs: 2, sm: 4, md: 6, lg: 8, xl: 10 },
    } as unknown,
    shadows: [...getShadows(mode)] as unknown,
    typography,
    customShadows: getCustomShadows(mode),
    mainColorChannels: {
      light: "67 89 113",
      dark: "231 227 252",
      lightShadow: "67 89 113",
      darkShadow: "19 17 32",
    },
  } as Parameters<typeof extendTheme>[0]);
}

export const uiTheme = createUiTheme("light");
export default uiTheme;
